### ISSUE TITLE
Allow use of `additionalProperties` in stored query schemas

### ISSUE THREAD

**Issue by ialarmedalien** [kbase/relation_engine#11]
This will require cleaning up the injection of `ws_ids` in `run_query` of `api_v1.py` -- see https://github.com/kbase/relation_engine/blob/develop/relation_engine_server/api_versions/api_v1.py#L53

**Comment by jayrbolton** [comment]
I mentioned in slack that I think this can be achieved most simply by removing this line: https://github.com/kbase/relation_engine/blob/develop/relation_engine_server/api_versions/api_v1.py#L63

That line is unnecessary in the logic of what's going on there, because line 76 will always overwrite a "ws_ids" param before sending the query to arango, and after validating with the json schema
